### ISSUE TITLE
Cannot access protected property Bavix\\LaravelClickHouse\\Database\\Query\\Builder::$wheres

### ISSUE THREAD

**Issue by dvcarrot** [bavix/laravel-clickhouse#6]
https://github.com/bavix/laravel-clickhouse/blob/a2ed9d221e66dbb160767af194104dc7178a0c33/src/Database/Eloquent/Builder.php#L671

**Comment by rez1dent3** [comment]
I was asked to add versions 9 and 10 to composer.json, but I didn't check them.

We switched to the standard mysql/postgres interface from clickhouse. More details here: https://clickhouse.com/docs/en/interfaces/mysql

**Comment by rez1dent3** [comment]
Hello. Many people asked to continue development. I'll try to find time.
