### ISSUE TITLE
Method Bavix\LaravelClickHouse\Database\Query\Builder::getCountForPagination does not exist

### ISSUE THREAD

**Issue by dvcarrot** [bavix/laravel-clickhouse#7]
```
Model::query()->paginate()
```

**Comment by rez1dent3** [comment]
Hello. This is a fork of the library: https://github.com/esazykin/laravel-clickhouse

I was asked to add versions 9 and 10 to composer.json, but I didn't check them.

We switched to the standard mysql/postgres interface from clickhouse. More details here: https://clickhouse.com/docs/en/interfaces/mysql

**Comment by rez1dent3** [comment]
Hello. Many people asked to continue development. I'll try to find time.
